version: '3.3'
services:
#nome do servico
  


  mongo:
    image: mongo:4.4.17
    ports:
      - 27017:27017  
    environment:
      - MONGO_INTIDB_ROOT_USERNAME=rootuser
      - MONGO_INTIDB_ROOT_PASSOWRD=rootpass
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
    restart: always
    depends_on:
      - mongo


  api-springboot-mongodb:

    #construido a partir de uma imagem oficial
    image: eclipse-temurin:17-jdk-focal
    
    #nome do conteiner
    container_name: api-springboot-mongodb

    #pastas compartilhadas
    volumes:
      #pasta do codigo fonte da aplicacao
      - "./app:/app"

    #porta a ser exposta
    # ports:
    #   - 8080:8080
  
    #artifício para manter o container aberto
    tty: true
  